#!/usr/bin/env python3
"""
Test script for Phi-3 integration with George
"""

import sys
import os
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / 'src' / 'george'))

def test_phi3_integration():
    """Test the Phi-3 integration."""
    print("🧪 Testing Phi-3 Integration with George")
    print("=" * 50)
    
    try:
        from llm_integration import create_george_ai
        print("✅ Successfully imported George AI module")
        
        # Create George AI instance
        george = create_george_ai(model="phi3:instruct")
        print("✅ Successfully created George AI instance")
        
        # Check if AI is available
        if george.is_available():
            print("✅ Phi-3 AI service is available")
            
            # Get model info
            info = george.get_model_info()
            print(f"📊 Model Info:")
            print(f"   - Current Model: {info['model']}")
            print(f"   - Service Available: {info['available']}")
            print(f"   - Available Models: {', '.join(info['available_models'][:3])}...")
            
            # Test a simple chat
            print("\n💬 Testing chat functionality...")
            test_message = "What are some key elements to consider when developing a fantasy character?"
            
            print(f"User: {test_message}")
            print("George AI: ", end="", flush=True)
            
            result = george.chat(test_message)
            if result['success']:
                print(f"{result['response'][:200]}...")
                print(f"\n✅ Chat test successful!")
                print(f"📝 Response length: {len(result['response'])} characters")
                print(f"🤖 Generated by: {result['model']}")
            else:
                print(f"❌ Chat test failed: {result.get('error', 'Unknown error')}")
                
        else:
            print("❌ Phi-3 AI service is not available")
            print("   Make sure Ollama is running and phi3:instruct is installed")
            
    except ImportError as e:
        print(f"❌ Failed to import George AI: {e}")
        print("   Check if all dependencies are installed")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
    
    print("\n" + "=" * 50)
    print("🎯 Test completed!")

if __name__ == "__main__":
    test_phi3_integration()